[AR-3114] Notify Systemd after update to config file
WIP!  It currently fails with:

Aug 25 13:19:50 i-019b1c24e0af5d565.rocketchat puppet[2568175]:
  Error: Could not find resource 'Systemd_refresh[rocket.service]'
  in parameter 'notify'
  (file: /etc/puppetlabs/code/environments/staging/modules/rocketchat/manifests/service.pp, line: 39)
  on node i-019b1c24e0af5d565.rocketchat